### ISSUE TITLE
Is it known which models are supported?

### ISSUE THREAD

**Issue by rdorsch** [nmakel/solaredge_modbus#17]
Hi,

can you tell if the SolarEdge SE5K inverter supports modbus TCP? I only saw modbus on RS485 in the documentation, but I may have missed something.

Thanks
Rainer

**Comment by nmakel** [comment]
Reading inverter values over Modbus (TCP) is supported by all inverters with firmware version 3 and higher.

Have a look at [this document](https://www.solaredge.com/sites/default/files/sunspec-implementation-technical-note.pdf), specifically the section "Modbus over TCP configuration."
