### ISSUE TITLE
inverter.read_all() not returning some keys

### ISSUE THREAD

**Issue by smcallis77** [nmakel/solaredge_modbus#26]
Hi,
In version 0.6.5, example.py does not seem to want to return the following keys ''c_manufacturer': 'SolarEdge', 'c_model': 'SE5000', 'c_version': '0003.2312', 'c_serialnumber': '7F1718EA', 'c_deviceaddress': 1" all other keys are returned starting with 'c_sunspec_did'.

It works in version 0.6.3 which is where the keylist above was obtained from.

So in example.py, line 29 values = inverter.read_all()

returns this dictionary:
{'c_manufacturer': 'SolarEdge', 'c_model': 'SE5000', 'c_version': '0003.2312', 'c_serialnumber': '7F1718EA', 'c_deviceaddress': 1, 'c_sunspec_did': 101, 'current': 13351, 'p1_current': 13351, 'p2_current': 0, 'p3_current': 0, 'current_scale': -3, 'p1_voltage': 2492, 'p2_voltage': 0, 'p3_voltage': 0, 'p1n_voltage': 0, 'p2n_voltage': 0, 'p3n_voltage': 0, 'voltage_scale': -1, 'power_ac': 3318, 'power_ac_scale': 0, 'frequency': 50018, 'frequency_scale': -3, 'power_apparent': 3323, 'power_apparent_scale': 0, 'power_reactive': 19400, 'power_reactive_scale': -2, 'power_factor': -9983, 'power_factor_scale': -2, 'energy_total': 15334336, 'energy_total_scale': 0, 'current_dc': 7543, 'current_dc_scale': -3, 'voltage_dc': 4465, 'voltage_dc_scale': -1, 'power_dc': 3368, 'power_dc_scale': 0, 'temperature': 2647, 'temperature_scale': -2, 'status': 5, 'vendor_status': 0}

In version 0.6.5 it returns this:
{'c_sunspec_did': 101, 'current': 15000, 'p1_current': 15000, 'p2_current': 0, 'p3_current': 0, 'current_scale': -3, 'p1_voltage': 2492, 'p2_voltage': 0, 'p3_voltage': 0, 'p1n_voltage': 0, 'p2n_voltage': 0, 'p3n_voltage': 0, 'voltage_scale': -1, 'power_ac': 3732, 'power_ac_scale': 0, 'frequency': 49990, 'frequency_scale': -3, 'power_apparent': 3736, 'power_apparent_scale': 0, 'power_reactive': 17500, 'power_reactive_scale': -2, 'power_factor': -9984, 'power_factor_scale': -2, 'energy_total': 15334366, 'energy_total_scale': 0, 'current_dc': 8546, 'current_dc_scale': -3, 'voltage_dc': 4432, 'voltage_dc_scale': -1, 'power_dc': 3788, 'power_dc_scale': 0, 'temperature': 2682, 'temperature_scale': -2, 'status': 5, 'vendor_status': 0}

I tried version 0.6.4 but I get the error 'UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 12: invalid start byte'. I assume this is related to #21.

In version 0.6.5, if I comment out the printing of the above keys, I get:

Inverter(xxxxxxxxxxxx:502, connectionType.TCP: timeout=1, retries=3, unit=0x1):

Registers:
        Type: Single Phase Inverter
        Status: Producing (Throttled)
        Temperature: 26.82°C
        Current: 150.00A
        Voltage: 249.20V
        Frequency: 49.99Hz
        Power: 3732.00W
        Power (Apparent): 3736.00VA
        Power (Reactive): 175.00VAr
        Power Factor: -99.84%
        Total Energy: 15334366Wh
        DC Current: 8.55A
        DC Voltage: 443.20V
        DC Power: 3788.00W

**Comment by nmakel** [comment]
Hi Steve, thanks for trying out the various versions. As you've already seen there have been some issues similar to yours. 

You don't mention getting any error output when using version 0.6.5, only that the dictionary keys are missing. Is this the case? If not, please post the exception.

There is a difference in string decoding between 0.6.3 and 0.6.5. All of the missing dictionary keys are strings. Would you mind changing the following line in version 0.6.5:

https://github.com/nmakel/solaredge_modbus/blob/8248c76d5aa45fb2a4b75df00ca611c8b31cbf80/solaredge_modbus/__init__.py#L255

To:

```
    decoded = data.decode_string(length * 2).decode("utf-8").replace("\x00", "").rstrip()
```

This should revert the decoding behavior to 0.6.3 style. I am curious whether this solves your issue, or if there is a problem elsewhere in the code.

If you feel comfortable on the command line, you could also try fetching the various registers manually by opening Python and executing the following -- remember to substitute the correct IP, port and unit of your inverter:

```
import solaredge_modbus
inverter = solaredge_modbus.Inverter(host="1.2.3.4", port=1502, unit=1)
inverter.read("c_manufacturer")
inverter.read("c_model")
inverter.read("c_version")
```
