### ISSUE TITLE
get error using example_influxdb

### ISSUE THREAD

**Issue by robi59italy** [nmakel/solaredge_modbus#27]
Hei
I'm getting this error..
example_influxdb.py", line 7, in <module>
    from influxdb import InfluxDBClient
ModuleNotFoundError: No module named 'influxdb'

is it something related to my influxdb configuration?

**Comment by nmakel** [comment]
You will need the python `influxdb` package. Either through your package manager, or through [pypi](https://pypi.org/project/influxdb/).
