### ISSUE TITLE
Example.py, 3-phase voltages, correct?

### ISSUE THREAD

**Issue by strebrah** [nmakel/solaredge_modbus#3]
In example.py all 3-phase voltages are the same (inverter.registers['p1_voltage']) ? Is this correct?

`print(f"\tPhase 1 voltage: {(values['p1_voltage'] * (10 ** values['voltage_scale'])):.2f}{inverter.registers['p1_voltage'][6]}")`
` print(f"\tPhase 2 voltage: {(values['p1_voltage'] * (10 ** values['voltage_scale'])):.2f}{inverter.registers['p1_voltage'][6]}")`
` print(f"\tPhase 3 voltage: {(values['p1_voltage'] * (10 ** values['voltage_scale'])):.2f}{inverter.registers['p1_voltage'][6]}")`

Thanks in advance, Thanks for writing this module.

**Comment by nmakel** [comment]
Nope, that's a silly mistake. Thanks for pointing it out!
