### ISSUE TITLE
No example on PyPi package

### ISSUE THREAD

**Issue by rdorsch** [nmakel/solaredge_modbus#31]
Hello,

I think the package on PyPi does not contain the example.py

(solaredge_modbus) rd@home:~/virtualenv/solaredge_modbus$ find -name example*
(solaredge_modbus) rd@home:~/virtualenv/solaredge_modbus$ 

If I download it from github it works flawless though.

Thanks
Rainer

**Comment by nmakel** [comment]
This seems to have changed in recent Python releases, as I remember the extra files being included previously. I can't find a dependable method of including the extra files in both the source and binary distributions -- it's a mess at the moment in Python packaging land.
