### ISSUE TITLE
current_scale glitch

### ISSUE THREAD

**Issue by rdorsch** [nmakel/solaredge_modbus#32]
Hi,

I just reviewed example.py and found that

print(f"\tCurrent: {(values['current'] * (10 ** values['temperature_scale'])):.2f}{inverter.registers['current'][6]}")

should probably be

print(f"\tCurrent: {(values['current'] * (10 ** values['current_scale'])):.2f}{inverter.registers['current'][6]}")

Both are reported by my inverter as -2, so this does not make a functional difference for me right now.

**Comment by nmakel** [comment]
Fixed, thanks!
