### ISSUE TITLE
Works perfectly!! I Sugget to add it to the PP-MANAGER

### ISSUE THREAD

**Issue by CreasolTech** [nmakel/solaredge_modbus#35]
Hi Niels, 
you plugins is really very good and well documented.
I just suggest you to add it to the PP-MANAGER and Domoticz Plugins Manager:
Check https://www.domoticz.com/wiki/Plugins .
These two plugins are commonly used to install other plugins automatically, using git.
Adding your plugin to the list of plugins supported by PP-MANAGER and Domoticz Plugins Manager requires just few minutes.
Thanks a lot again for your good plugin.
Paolo

**Comment by CreasolTech** [comment]
I have to add that I'm using the domoticz plugin by Addie Janssen
https://github.com/addiejanssen/domoticz-solaredge-modbustcp-plugin
Bye.
Paolo

**Comment by nmakel** [comment]
Thanks for the kind words, Paolo. I'm not a domoticz user, so I'm happy to have @addiejanssen provide his plugin :)
