### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by rploeg** [nmakel/solaredge_modbus#56]
Hi,

When I run the example file with my IP and port of my solaredge main convert (have in total 3 + battery) I get this error directly:

pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] ModbusTcpClient(192.168.1.246:502): Connection unexpectedly closed 0.000037 seconds into read of 8 bytes without response from unit before it closed connection

I know for sure that I can connect to this IP and port, becasue with NodeRed I can read the modbus via the modbus module there. Any thoughts?

**Comment by nmakel** [comment]
Is the inverter actually listening on port 502 and not 1502?

**Comment by rploeg** [comment]
yes

From: niels ***@***.***>
Date: Friday, 30 September 2022 at 10:58
To: nmakel/solaredge_modbus ***@***.***>
Cc: Remco Ploeg ***@***.***>, State change ***@***.***>
Subject: Re: [nmakel/solaredge_modbus] Connection problem (Issue #56)

Is the inverter actually listening on port 502 and not 1502?
